### ISSUE TITLE
As an User, I am able to upload files to OSP

### ISSUE THREAD

**Issue by Monal5031** [anitab-org/open-source-programs-backend#10]
## Description
As an User, I am able to upload files to OSP

## Mocks
N/A

### Update [Required]
- [ ] Add boto to requirements
- [ ] Write script to use boto to upload media to AWS bucket
- [ ] Store the link of the media in models
- [ ] Write tests

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3-4 days

**Comment by abha224** [comment]
Closing this issue since the uploading functionality is implemented at the frontend side.
