### ISSUE TITLE
Bug: Remove irrelevant option from checklist in PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/open-source-programs-backend#105]
### Describe the bug
There is a option ` I have written Kotlin Docs whenever is applicable` under the checklist in PULL_REQUEST_TEMPLATE.md. (I think due to copy-pasting the file from some other project).

### To Reproduce
1. Go to https://github.com/anitab-org/open-source-programs-backend/blob/develop/.github/PULL_REQUEST_TEMPLATE.md
2. See error

### Expected behavior
The option should be removed from the checklist.

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by devkapilbansal** [comment]
@Aaishpra @Rahulm2310 aren't we not covering this in #91 ??

**Comment by arkumari2000** [comment]
If this is a valid issue and not get covered in any issue, Can I work on it?

**Comment by Aaishpra** [comment]
> @Aaishpra @Rahulm2310 aren't we not covering this in #91 ??

You are right@devkapilbansal we can suggest this in the linked PR in #91
Thanks for mentioning it here.

**Comment by devkapilbansal** [comment]
Closing this as there is an issue already for this.

**Comment by Rahulm2310** [comment]
> @Aaishpra @Rahulm2310 aren't we not covering this in #91 ??

@devkapilbansal  Yeah, we can cover it in #91. Thanks
