### ISSUE TITLE
Bug : Incorrect link to reporting guidelines in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/open-source-programs-backend#111]
### Describe the bug
The links to reporting guidelines is incorrect in the code of conduct file.

### To Reproduce

1. Go to 'https://github.com/anitab-org/open-source-programs-backend/blob/develop/CODE_OF_CONDUCT.md'
2. Scroll down to Reporting guidelines section
3. Click on  [Reporting Guidelines](https://github.com/anitab-org/open-source-programs-backend/blob/develop/reporting_guidelines.md) 

### Expected behavior
Links to the file should be corrected :

Reporting guidelines: https://github.com/anitab-org/open-source-programs-backend/blob/develop/REPORTING_GUIDELINES.md

### Screenshots
![Error_reporting](https://user-images.githubusercontent.com/66437295/110085328-f867bc80-7db6-11eb-8537-dca08dd48c41.gif)

**Comment by Amulya-coder** [comment]
@isabelcosta can you please add a label to it as `First-Timer only` issue. Thanks 🙂

**Comment by nlok5923** [comment]
i would like t work on it as it will be mine first contribution to this open-source-programs backend.

**Comment by codesankalp** [comment]
Assigning you @nlok5923 !
