### ISSUE TITLE
Add codecov badge in README

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-backend#114]
## Description
As a developer,
I need to see the coverage report in the README,
so that I can know about the coverage and create more issues to increase coverage.

## Mocks

[![codecov](https://codecov.io/gh/anitab-org/open-source-programs-backend/branch/develop/graph/badge.svg)](https://codecov.io/gh/anitab-org/open-source-programs-backend)

### Update [Required]
- [ ] Add codecov badge of coverage in README.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by himanshu007-creator** [comment]
Can i work on this issue?
I have searched for it ,but to make it work , person requires admin / write rights of the repo.
![2021-03-07](https://user-images.githubusercontent.com/65963997/110247207-16891480-7f91-11eb-8665-d26b65bb037e.png)

**Comment by codesankalp** [comment]
Assigning you @himanshu007-creator.
There are no permissions required for adding codecov badge. 
And I don't know what you have searched but I am sure that there are no permissions required for adding a badge.

You just have to add a badge by adding this in the readme @himanshu007-creator :
`[![codecov](https://codecov.io/gh/anitab-org/open-source-programs-backend/branch/develop/graph/badge.svg)](https://codecov.io/gh/anitab-org/open-source-programs-backend)`
