### ISSUE TITLE
bug: Secret key not passed in Github Workflow

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/open-source-programs-backend#118]
### Describe the bug
GitHub CI raises ValueError as Secret Key is not passed in environment.

### To Reproduce
1. Go to `https://github.com/anitab-org/anitab-forms-backend/actions`
2. Navigate through some latest workflow runs

### Expected behavior
Workflows should run without raising any error.

### Additional context
You can refer official doc [here](https://docs.github.com/en/actions/reference/environment-variables)

**Comment by ashwinijha6** [comment]
@devkapilbansal I would like to work on this

**Comment by devkapilbansal** [comment]
Sorry, @ashwinijha6 This issue is first timer only and you already create a PR on #75

**Comment by ashwinijha6** [comment]
Ok @devkapilbansal 👍
