### ISSUE TITLE
Change links and text to the current repository name

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-backend#120]
## Description
As a contributor,
I need all the links and text that is using `open-source-programs-backend` changed into `anitab-forms-backend`,
so that there is no confusion and 404 pages for newcomers.

### Update [Required]
- [ ] Change `open-source-programs-backend` to `anitab-forms-backend`.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours.

**Comment by HeroicHitesh** [comment]
@codesankalp I would like to work on this

**Comment by codesankalp** [comment]
Assigning you @HeroicHitesh .

**Comment by HeroicHitesh** [comment]
@codesankalp There are a few folders and files whose name contains `osp` what should that be renamed to?

**Comment by codesankalp** [comment]
Just change links and text and avoid changing any code.
