### ISSUE TITLE
Bug : Install requirements first in docker

### ISSUE THREAD

**Issue by epicadk** [anitab-org/open-source-programs-backend#122]
### Describe the bug

This will result in the requirements being downloaded again even if small changes are made to the code. 

### Expected behavior

Install requirements before copying the code.  

### Resources that could help 

https://docs.docker.com/compose/django/
https://github.com/anitab-org/stem-diverse-tv/blob/master/Dockerfile

**Comment by isabelcosta** [comment]
@epicadk can you provide any documentation a link a contributor can look to, to complete this? is this already done in any of our projects for example?

**Comment by codesankalp** [comment]
@isabelcosta 4th line of point 3 of this page https://docs.docker.com/compose/django/
I think @epicadk is working on docker (stem-diverse-tv: [here](https://github.com/anitab-org/stem-diverse-tv/blob/master/Dockerfile) ) when we discussed it.
It will save time during development and other tasks by skipping installation again and again.

**Comment by epicadk** [comment]
> @isabelcosta 4th line of point 3 of this page https://docs.docker.com/compose/django/
> I think @epicadk is working on docker (stem-diverse-tv: [here](https://github.com/anitab-org/stem-diverse-tv/blob/master/Dockerfile) ) when we discussed it.
> It will save time during development and other tasks by skipping installation again and again.

Also has been done on mentorship android.

**Comment by epicadk** [comment]
I'd like to work on this.

**Comment by codesankalp** [comment]
Assigning you @epicadk.
