### ISSUE TITLE
Create env template

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-backend#136]
## Description
As a Developer,
I need a template for environment variables,
so that I can more focus on development and not on setting up the environments.

### Update [Required]
- [ ] [Create `.env.template` file in root project directory].
- [ ] [Add all the env variables with descriptive comments].

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Amulya-coder** [comment]
@codesankalp I would like to work on this issue.

**Comment by codesankalp** [comment]
Assigning you @Amulya-coder

**Comment by Amulya-coder** [comment]
@codesankalp I have created a pr can you please review it.
