### ISSUE TITLE
Change links and text to the current repository name

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/open-source-programs-backend#139]
### Description
As a contributor,
I need all the links and text that is using` open-source-programs-backend` changed into `anitab-forms-backend`,
so that there is no confusion and 404 pages for newcomers.

### Update Required

- [ ] Change open-source-programs-backend to anitab-forms-backend.

### Definition of Done
 

- [ ] All of the required items are completed.

  

- [ ]   Approval by 1 mentor.

### Estimation

3 hours.

**Comment by untari** [comment]
Hi, does anyone working on this issues? If not may I work on it?

**Comment by Aaishpra** [comment]
Assigned you @untari

**Comment by untari** [comment]
Hi @Aaishpra  I did check all the files, the link and text has been change to the current repository name

**Comment by Aaishpra** [comment]
Hey @untari I see some instances of Open Source program backend in the readme, (in the main heading and then in contact us section) can you please change that? if you didn't find anything in other files.

**Comment by untari** [comment]
will do, thanks for the heads up

**Comment by Aaishpra** [comment]
[Here](https://github.com/anitab-org/anitab-forms-backend#open-source-programs-backend) and in `#open-source-programs` in [contact](https://github.com/anitab-org/anitab-forms-backend/blob/develop/README.md#contact)

**Comment by untari** [comment]
hi @Aaishpra I'm not be able to make the changes, as everytime I push my changes it said run failed. you might want to unassigned me. thanks

**Comment by Aaishpra** [comment]
You can submit a PR @untari ,no issues if checks are failing, we can still review it.
