### ISSUE TITLE
Add travis CI file

### ISSUE THREAD

**Issue by Monal5031** [anitab-org/open-source-programs-backend#14]
## Description
As a developer/QnA, I need to test the new PRs on CIs

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] Add a travis CI file with minimal config for now

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by isabelcosta** [comment]
Will close this one and create a new issue to do this instead with GitHub Actions
