### ISSUE TITLE
Remove djangorestframework-jwt as it is deprecated

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-backend#157]
### Describe the bug

While using python3.9 djangorestframework-jwt gives conflict with djangorestframework-simplejwt and the setup became complex.

### To Reproduce
1. Install by following steps in README.

### Expected behavior
No errors and simple installation.

### Screenshots
![image](https://user-images.githubusercontent.com/56037184/135765719-361bb322-409d-4272-881c-207d8f4d7e7f.png)

### Desktop (please complete the following information):
 - OS: Ubuntu & Windows
 - Browser Chrome

### Additional context
There is only one place where we are using djangorestframework-jwt:
https://github.com/anitab-org/anitab-forms-backend/blob/dd72f65ce5e43cb836be2b20572f51137dd8c518/token_auth/serializers/register.py#L3

Removing this will solve this issue.

**Comment by moazfarrukh** [comment]
can i be assigned with this issue?

**Comment by isabelcosta** [comment]
@moazfarrukh it's yours!
@codesankalp thank you for creating this 🙌🏾

**Comment by moazfarrukh** [comment]
@codesankalp @isabelcosta i have found out that it all works perfectly with the version 4.6.0 of simple jwt 
problems only occur while using the versions 4.4.0 and 4.8.0
so changing the requirements.txt  to djangorestframework-simplejwt==4.6.0 
fixes the issue
should i make a pull request with this change?

**Comment by codesankalp** [comment]
@moazfarrukh Sorry for the late reply, but I think removing it will be the better option here because the package is deprecated and will cause problems in the future.

**Comment by moazfarrukh** [comment]
> @moazfarrukh Sorry for the late reply, but I think removing it will be the better option here because the package is deprecated and will cause problems in the future.

Ok i will change my pull request

**Comment by moazfarrukh** [comment]
@codesankalp i have made a pull request. awaiting review
