### ISSUE TITLE
Rename references to Open Source programs to AnitaB Forms on Docusaurus

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-backend#160]
## Description

Rename references to Open Source programs to AnitaB Forms on Docusaurus.

Here's an example:
![docusaurus main page](https://user-images.githubusercontent.com/11148726/137644892-fc560457-ff7f-4b3b-b9ea-e38a943a49c7.png)

### Update [Required]
- [ ] Rename references to Open Source programs to AnitaB Forms on Docusaurus pages

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by pranjal-arora** [comment]
Hello! I would like to take up this issue! Please do make me an assignee.

**Comment by isabelcosta** [comment]
sure @pranjal-arora :)

**Comment by pranjal-arora** [comment]
@isabelcosta hey, do I just have to rename "Open Source Programs" to "AnitaB Forms" in the files:- docusaurus.config.js and index.js 
OR do I also need to rename it in the yml files (qa-checks.yml) and markdown files as well (eg. README.md, CONTRIBUTING.md, Home.md etc.) ?

**Comment by isabelcosta** [comment]
@pranjal-arora only docusaurus related files. The rest is optional, but if you add them, I'll accept those as well :)
