### ISSUE TITLE
doc: update ReadMe file

### ISSUE THREAD

**Issue by abha224** [anitab-org/open-source-programs-backend#23]
## Description
The versions of Django and Django rest framework used for the project Open source programs(OSP) is not mentioned in the readme file and need to be added.

versions used are: 
Django 3.0.7
Django rest framework 3.11.0  
 
For additional information refer requirements.txt file.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 mins

**Comment by vj-codes** [comment]
Heyy can I work on this issue?The versions are supposed to be added in tech stack section right?

**Comment by abha224** [comment]
@vj-codes Hi!! Yes, go ahead. I'll assign the issue to you :)
Yep, the versions are supposed to be added to the tech stack section.

**Comment by vj-codes** [comment]
@abha224 thanks I'll send a PR soon:)
