### ISSUE TITLE
Error in DB setup instructions in README

### ISSUE THREAD

**Issue by bismitaguha** [anitab-org/open-source-programs-backend#32]
### Describe the bug
Error in the DB setup instructions mentioned in the `README.md`.

### To Reproduce
1. While setting up with the DB instructions mentioned, errors are thrown.
2. See error

### Expected behavior
Setup instructions should work fine and smoothly

### Screenshots
N/A

### Desktop (please complete the following information):
All versions

### Additional context
N/A

**Comment by Aaishpra** [comment]
@bismitaguha the first thing I noticed was the link to install postgresql it took to install the package from source code, in my view, it will be easier to install the package by directly downloading it, so the link should take us to the download page.Please correct me if i am wrong.

**Comment by bismitaguha** [comment]
The installation of Postgres is not the same a DB setup!!! The DB setup instructions are wrong. You won't be able to correctly set it up with the commands mentioned.

**Comment by shivanii10** [comment]
@bismitaguha  can i work on this ?

**Comment by riyasingh1004** [comment]
I have just setup the database locally on my laptop and have resolved the setup errors. Since I use both windows and Ubuntu I can add setup instructions for both. Can you,please assign me this issue.

**Comment by untari** [comment]
I would like to work on this issue please

**Comment by vj-codes** [comment]
Assigning you @untari 
Happy documenting!

**Comment by isabelcosta** [comment]
fixed by #49
