### ISSUE TITLE
Final Phase

### ISSUE THREAD

**Issue by abha224** [anitab-org/open-source-programs-backend#4]
## Description
As a user , I need to be able to register/login with the OSP website.

**Comment by aakankshaagr** [comment]
Can I work on this issue if it's available?

**Comment by isabelcosta** [comment]
Will close this, as it does not make a lot of sense, as it is not linked to issues and not properly described. This is from GSoC 2020. @aakankshaagr there are other issues, could you  look at those, happy to assign you another from there.
