### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by untari** [anitab-org/open-source-programs-backend#44]
### Describe the bug
Error in DB Setup

### To Reproduce
1. sudo -i -u postgres
2. createuser
3. psql
4. CREATE DATABASE
5. \c osp 
6. GRANT **ON** PRIVILEGES ON DATABASE systersdb to osp;
      **ERROR:  syntax error at or near "ON"
      ERROR:  database "systersdb" does not exist**

### Expected behavior
first error it is in command **GRANT ON** because the command syntax it's wrong   

second error
From the main/setting.py I figured the default bd is **osp** 
so when I do command **systersdb to osp**  I got an error as it said systersdb does not exits.

### Screenshots
![screen0](https://user-images.githubusercontent.com/49097652/98936252-48c0c300-2517-11eb-8e1c-81efcf496747.png)
![screen02](https://user-images.githubusercontent.com/49097652/98946127-1074b100-2526-11eb-9b85-a44800bd9fdf.png)

### Desktop (please complete the following information):
All version

### Additional context
N/A

**Comment by devkapilbansal** [comment]
@untari you should wait for your issue to be accepted and assigned to you before making a pull request. Although the issue seems valid but can you please edit it and use the bug report template

**Comment by Aaishpra** [comment]
Hi, @untari thanks for opening this issue, Although this is not a valid issue it's a  copy of #32. Another Thing this project currently is not very active so, if you need to be assigned to any issue or need help with anything related to the project please try to ask on Zulip chat channels. 

Thanks, and please close this issue and PR here and ask to be assigned #32.

Happy Hacking.

Tagging @isabelcosta @vj-codes for their views regarding this.

**Comment by vj-codes** [comment]
@Aaishpra yes I agree and will close the issue now, the PR however is already closed. Thank you for bringing it up. Zulip works the best for communication! 
Also @untari thank you for creating the issue :)
