### ISSUE TITLE
Login and password reset

### ISSUE THREAD

**Issue by DhruviJ17** [anitab-org/open-source-programs-backend#47]
Login is required after registeration of a user. Hence, adding a login view.

Password reset feature, where an email is sent on the user's email id and user can reset the password.

**Comment by utkarsh147-del** [comment]
I want to work on this.Please assign this work to me.

**Comment by codesankalp** [comment]
Closing this issue as it is not approved and the login feature is present (JWT Authentication).
Although, we will create a new issue in the future for password resetting.
