### ISSUE TITLE
Write Better Setup Instructions for setting the project.

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/open-source-programs-backend#48]
### Describe the bug

As a developer, I would need the correct setup Instructions to set up the projects locally and start working on their issues. But the current Setup instructions aren't correct as well as incomplete and are specifically targeted at users with Linux as Operating System.

### To Reproduce
1. Go to https://github.com/anitab-org/open-source-programs-backend
2. Scroll down to Setup.
3. See the Instructions.

![image](https://user-images.githubusercontent.com/66299533/105016391-96eac900-5a68-11eb-8acc-72908c8f67cd.png)

There should be instructions for Windows users to set up the database

![image](https://user-images.githubusercontent.com/66299533/105015020-1bd4e300-5a67-11eb-925d-6df17c4d2255.png)

The cd command should be after the virtual environment commands. Also the steps are incomplete.

### Expected behavior

Clear, Concise and Correct Instructions to set up the project and database for different operating Systems(preferably Windows, Linux, mac)

### Desktop (please complete the following information):
 - OS: Ubuntu 20.04
 - Browser Firefox web Browser
 - Version --

**Comment by khushishikhu** [comment]
@isabelcosta  can you please assign this issue to me

**Comment by vj-codes** [comment]
The command  process is correct as it is right now @Aaishpra @khushishikhu 
First one it takes the user to the project 
Second one creates a virtual env
Thrid one activates it and then install and run

However for windows it is `venv\Scripts\activate` so I suggest keeping the order same just replacing the command

**Comment by INNOVATIVEGAMER** [comment]
@khushishikhu Can you also add screenshots of creating user and database using PGAdmin4 in windows.(administration tool for postgresql in windows) 
As PGAdmin4 provides graphical UI for the users it will be very easy for users to follow. 
You can find PGAdmin4 at the following path in windows : `PostgreSQL\13\pgAdmin 4\bin`

**Comment by khushishikhu** [comment]
> @khushishikhu Can you also add screenshots of creating user and database using PG4Admin in windows.(administration tool for postgresql in windows) 
> As PG4Admin provides graphical UI for the users it will be very easy for users to follow. 
> 
> 

@INNOVATIVEGAMER Thank you for the suggestion. I will add that too

**Comment by khushishikhu** [comment]
@isabelcosta @vj-codes @Aaishpra I have made the PR. Please review it and let me know the required changes needs to be done
