### ISSUE TITLE
Create a Docker file to run the backend

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-backend#51]
## Description
As a developer,
I need a way to run the backend using Docker,
so that I can run the project with one command without the need to setup my local dev environment.

### Update [Required]
- [ ] Create a Dockerfile to run the project using one command
- [ ] Add documentation on running the program using Docker on README

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by chinmaym07** [comment]
Hey @isabelcosta I want to try this .

**Comment by isabelcosta** [comment]
@chinmaym07 you are already assigned another issue. Would you like to give up that issue for this one?

**Comment by devkapilbansal** [comment]
Hi @isabelcosta I want to give it a try

**Comment by isabelcosta** [comment]
Ok, @devkapilbansal I will assign this to you since you are not assigned to an issue on this repository, at the moment :)
