### ISSUE TITLE
Add GitHub Actions workflow to run tests

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-backend#53]
## Description

As a developer,
I need ensure the tests are passing in the CI pipeline,
so that I can know that my code is not failing before merging.

### Update [Required]
- [ ] Create GitHub actions workflow to run tests

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Soumi7** [comment]
I would like to work on this issue.

**Comment by codesankalp** [comment]
@isabelcosta But I can't see any test written in this project repo.
I want to give this a try.

**Comment by isabelcosta** [comment]
> I can't see any test written in this project repo.

@codesankalp Yey, this means there are a lot of issues to come for this repo!

Ok, so because of that maybe this should come after at least 1 test. I will put this on hold then. If any of you comes with an idea for this, would be great if you could create an issue @Soumi7 @codesankalp

**Comment by codesankalp** [comment]
@isabelcosta now some tests have been merged can I write a workflow for running tests also?

**Comment by isabelcosta** [comment]
Sure :) @codesankalp
