### ISSUE TITLE
Add test structure and some test for token_auth register serializer

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-backend#56]
### Is your feature request related to a problem? Please describe.
As this repo does not contain any test, so create the test files structure so that it is modular and write some tests for token_auth.

### Describe the solution you'd like
Make the structure of the test, add some test and update README.

### Describe alternatives you've considered
-

### Additional context
-

**Comment by codesankalp** [comment]
Will add more tests soon. :relaxed:

**Comment by isabelcosta** [comment]
No need to add them all in this PR @codesankalp :) it helps to review if PRs are really focused on a specific task. Feel free to create other issues to cover tests for other specific features.
