### ISSUE TITLE
docs: Add link in README

### ISSUE THREAD

**Issue by khushishikhu** [anitab-org/open-source-programs-backend#58]
### Is your feature request related to a problem? Please describe.
The Contributing section of the README.md doesn't have the link in the "contributing guidelines"

### Describe the solution you'd like
Add the link of AnitaB.org contributing guidelines over there

### Additional context
This is required for any newcomer to first read the contributing guidelines before making any contribution.

**Comment by isabelcosta** [comment]
Perfect! Thank you @khushishikhu ! Do you want to work on this or leave it to a first timer?

**Comment by khushishikhu** [comment]
@isabelcosta  i would like to work on this issue

**Comment by isabelcosta** [comment]
Go ahead @khushishikhu
