### ISSUE TITLE
docs: Add a documentation section in the README.md

### ISSUE THREAD

**Issue by khushishikhu** [anitab-org/open-source-programs-backend#61]
### Is your feature request related to a problem? Please describe.

Add a section in README.md which directs us to the wiki of the backend part of the project (open-source-programs-backend)

### Describe the solution you'd like

Create a "Documentation" section with:
- link to the wiki for further information regarding the community
- link to open sessions which include the meeting minutes, 
- link to the video of GSoC: https://youtu.be/3A746GppZ0Y
- link of adding a video of setting up the project: https://youtu.be/_b2RQGbYN9w
- link of the question in zulip chats.
 
You can check these resources on this [zulip message](https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs/topic/Open.20Sessions/near/225236028)

**Comment by ashwinijha6** [comment]
@khushishikhu & @isabelcosta does this require creating an entirely new wiki page or editing the previous one because I can see a wiki page in the README.md though it has some mistakes?

**Comment by khushishikhu** [comment]
@ashwinijha6 Wiki is already there but you just have to add a section which has the link to that

**Comment by Amulya-coder** [comment]
@khushishikhu the wiki link is already mentioned in the Setup section so why you included it in the description do we have a separate wiki page for the backend? I think it is better to change the title from wiki section to <b>Project Documentation section</b> which sounds more suitable and not confusing the newcomers as it includes the meeting minutes + zulip chats +video of the GSoC as you have mentioned in the description.

**Comment by khushishikhu** [comment]
> @khushishikhu the wiki link is already mentioned in the Setup section so why you included it in the description do we have a separate wiki page for the backend? I think it is better to change the title from wiki section to Project Documentation section which sounds more suitable and not confusing the newcomers as it includes the meeting minutes + zulip chats +video of the GSoC as you have mentioned in the description.

@Amulya-coder yes we have a separate wiki page for the backend, the link which is mentioned in the setup directs us to the wiki page of frontend part.

**Comment by Amulya-coder** [comment]
@khushishikhu Yes, I know that the wiki page mentioned in the readme will direct us to the frontend part could you please give the appropriate links within the description also it'll be good to provide the specified links that are getting to be used in the issue.

**Comment by Amulya-coder** [comment]
I would like to work on this issue. Can I please be assigned

**Comment by khushishikhu** [comment]
> I would like to work on this issue. Can I please be assigned

@isabelcosta  can you please assign this issue to @Amulya-coder

**Comment by isabelcosta** [comment]
> @isabelcosta can you please assign this issue to @Amulya-coder

@Amulya-coder will assign to you.

> @khushishikhu & @isabelcosta does this require creating an entirely new wiki page or editing the previous one because I can see a wiki page in the README.md though it has some mistakes?

Feel free to create an issue about the Wiki mistakes ;)

**Comment by isabelcosta** [comment]
@khushishikhu @Amulya-coder I updated the issue description + title to present information in a clearer way 😉

**Comment by isabelcosta** [comment]
@Amulya-coder how you are getting on with this issue?

**Comment by Amulya-coder** [comment]
Yes working on it. I will try to send a pr asap @isabelcosta 👍.
