### ISSUE TITLE
Integrate Code Linters to enhance/ensure code quality

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/open-source-programs-backend#62]
### Is your feature request related to a problem? Please describe.
It is necessary for every project to follow some guidelines about how the code should be written, maintained and all. But this misses guidelines related to code quality.

### Describe the solution you'd like
* Research about some good code linters, PEP8 Formatter (As the code is written in Python)
* Add brief description about them in Readme
* Format the code with the linters
* Add Github workflows to ensure the guidelines are followed by every contributor.

### Describe alternatives you've considered
There are a variety of options that we can look into:-
* Flake8 - Ensures some PEP8 guidelines and best practices
* Pylint - Linter for Python
* Isort - Sort the imports etc in alphabetic order
* Black - Ensures consistency (For eg:- converting all single quotes to double quotes)

### Additional context
Black formatter is included in [mentorship-backend](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/workflows/black.yml) and can give an idea on how to approach the problem

**Comment by devkapilbansal** [comment]
@isabelcosta please label this issue.

P.S. - I will leave this issue for others as it is also an easy issue. If no one takes this soon, then I would like to work on this.

**Comment by isabelcosta** [comment]
@devkapilbansal I see this and you did an amazing job writing the description for this issue 👏 💯 🙌 The additional context, the potential alternatives, etc. Very very well done 👏 Thank you for being so detailed here

**Comment by codesankalp** [comment]
@isabelcosta @devkapilbansal Can you assign me this issue?
As this pull request https://github.com/anitab-org/open-source-programs-backend/pull/57 needs review I would like to solve another issue :smiley:

**Comment by isabelcosta** [comment]
Done @codesankalp
