### ISSUE TITLE
docs: Include licence section in Readme

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/open-source-programs-backend#69]
### Is your feature request related to a problem? Please describe.
It's good to mention about the license under which the organization follows. Currently, there is no license added in the readme.

### Describe the solution you'd like
Add license section in the readme this is a great way to encourage more free, open-source code.

### Additional context
Here's is the link: https://github.com/anitab-org/open-source-programs-backend/blob/develop/LICENSE

**Comment by ayan-biswas0412** [comment]
@Amulya-coder can I work in this issue ?? I can add this type of badges also 
<img width="918" alt="image" src="https://user-images.githubusercontent.com/52851184/107850712-6b21ef80-6e2a-11eb-875d-0a60d6712592.png">

**Comment by ayan-biswas0412** [comment]
@Amulya-coder I have done the previous job in the [PR](https://github.com/anitab-org/open-source-programs-web/pull/79) can you assign me to this ?

**Comment by Amulya-coder** [comment]
@ayan-biswas0412 you can work on one issue atm wait for the maintainer to label this issue. Thanks 🙂.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 you can work on one issue atm wait for the maintainer to label this issue. Thanks 🙂.

Sure 😀

**Comment by isabelcosta** [comment]
> @Amulya-coder can I work in this issue ?? I can add this type of badges also
> <img alt="image" width="918" src="https://user-images.githubusercontent.com/52851184/107850712-6b21ef80-6e2a-11eb-875d-0a60d6712592.png">

this would be another issue @ayan-biswas0412 ;) feel free to create it

**Comment by isabelcosta** [comment]
@ayan-biswas0412 I know you have been assigned the same issue on web repository, so I will leave this available for a newcomer in this repo. Feel free to contribute to other first timers only issues in this repository

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 I know you have been assigned the same issue on web repository, so I will leave this available for a newcomer in this repo. Feel free to contribute to other first timers only issues in this repository

yes thanks @isabelcosta for reviewing my PR and thanks for the approval 🥰

**Comment by ayan-biswas0412** [comment]
> > @Amulya-coder can I work in this issue ?? I can add this type of badges also
> > <img alt="image" width="918" src="https://user-images.githubusercontent.com/52851184/107850712-6b21ef80-6e2a-11eb-875d-0a60d6712592.png">
> 
> this would be another issue @ayan-biswas0412 ;) feel free to create it

yah sure

**Comment by Subhangini** [comment]
Please assign this issue to me .I would like to work on it
