### ISSUE TITLE
docs: add good badges to the readme

### ISSUE THREAD

**Issue by ayan-biswas0412** [anitab-org/open-source-programs-backend#70]
### Is your feature request related to a problem? Please describe.
there are number of good looking badges available for the Github Readme some of are given below in the image 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/52851184/107857771-a4705480-6e56-11eb-9576-ea282ff10862.png">

here some more badges are available . [Badges](https://github.com/Naereen/badges)
please add the badges shown in the image only and the above link is only for future reference purpose

### Describe the solution you'd like
This badges can be added easily and here is the repo where you can find those in [readme](https://github.com/anitab-org/anitab-org.github.io/blob/develop/README.md) file don't forget to change the repository links in the badges

### Additional context
This issue can be a good first timers issue and as per the context of the [discussion](https://github.com/anitab-org/open-source-programs-backend/issues/69#issuecomment-778649620) I have opened this issue even I can work for this

**Comment by ayan-biswas0412** [comment]
@isabelcosta please add your thoughts on it

**Comment by isabelcosta** [comment]
@ayan-biswas0412 this looks great! I would just not add fork and stars badge, since that is already part of GitHub UI :) i will add the first timer only label then ;) Thank you for creating this issue 🙌🏾

**Comment by ayan-biswas0412** [comment]
@isabelcosta I have updated the issue , Can I please work for this ? ☺️ and please also suggest me some issues based on ReactJS development (if available) I can work for that also

**Comment by isabelcosta** [comment]
@ayan-biswas0412 issues base on react development would be on the web repository ;) What about leaving this issue for a "first timer only", I can help you come up with react dev issues if none are available on https://github.com/anitab-org/open-source-programs-web. Are you on Zulip? We'll soon have the documentation section that can help you find what is missing from the MVP of this project and come up with more issues

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 issues base on react development would be on the web repository ;) What about leaving this issue for a "first timer only", I can help you come up with react dev issues if none are available on https://github.com/anitab-org/open-source-programs-web. Are you on Zulip? We'll soon have the documentation section that can help you find what is missing from the MVP of this project and come up with more issues

yeah let's leave it to for first-timers-only and I will look up on the repo you mentioned and I am in Zulip also

**Comment by rmpsc** [comment]
Hi! First timer here. May I work on this issue? :)

**Comment by isabelcosta** [comment]
It's yours now @rmpsc :)
