### ISSUE TITLE
Document the env variables needed to run the backend

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/open-source-programs-backend#71]
## Description
As a developer,
I need to know which environment variables,
so that I can run the project.

There is documentation missing about the environment variables needed to have the project running.

### Update [Required]
- [ ] Update README with the environment variables needed to run the project and how to get them

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Rahulm2310** [comment]
@isabelcosta I would like to be assigned. Thanks 🙂

**Comment by isabelcosta** [comment]
This is more like a user story, than a bug in the project, so i updated the issue description using this template https://github.com/anitab-org/open-source-programs-backend/blob/develop/.github/ISSUE_TEMPLATE/user-story.md @Rahulm2310

**Comment by isabelcosta** [comment]
Sure assigned it to you @Rahulm2310 :)

**Comment by isabelcosta** [comment]
@Rahulm2310 any progress on this? Do you need any help?

**Comment by Rahulm2310** [comment]
@isabelcosta What more environment variables do we need to add in addition to zulip_id and sendgrid_api_key. I just created a GIF to show how to get zulip config and zulip id. 

![zulip-download-env](https://user-images.githubusercontent.com/54268438/107988857-e6380100-6ff6-11eb-809a-154ceb8e6f6b.gif)

![zulip-download-env-part2](https://user-images.githubusercontent.com/54268438/107988869-ea641e80-6ff6-11eb-98d1-52a78020c835.gif)

![zulip-download-env-part3](https://user-images.githubusercontent.com/54268438/107988872-ec2de200-6ff6-11eb-9042-407be0a7d1c8.gif)

Please share your suggestions.

**Comment by isabelcosta** [comment]
That is amazing 🤩 @Rahulm2310 
However no need for a GIF, just text is enough for this on README. This GIF can still leak your keys.
Can you run the backend properly with those 2 env vars? If so, then those are the only needed.
Feel free to submit a PR with documentation.

**Comment by codesankalp** [comment]
@Rahulm2310 Just a suggestion adding `django_secret_key` and `database config` as environment variables will be good here :relaxed:

**Comment by Rahulm2310** [comment]
@codesankalp Aren't these in the settings.py file?

**Comment by codesankalp** [comment]
> @codesankalp do we need these to run the project locally as I don't have these in my env.

According to the code, we don't need these to run the project locally.
But it will be a good practice if we can load `django_secret_key` and `database config` as env variables like in mentorship-backend.
But this issue is only related to the documentation you can skip this part as the project is running locally without these variables.

**Comment by codesankalp** [comment]
> @codesankalp Aren't these in the settings.py file?

Yes, they are present but I gave the suggestion for importing these as env variables in the code.
But again this issue is related to the document part you can skip this :relaxed:

**Comment by isabelcosta** [comment]
@codesankalp I just saw your suggestions here. Those make a lot of sense, I was now looking into the code and creating issue based on that. Can you create one issue to make database values into environment variables?
