### ISSUE TITLE
docs: Link to reporting guidelines incorrect in code_cf_conduct.md

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/open-source-programs-backend#73]
### Describe the bug
Link to reporting guidelines incorrect in code_cf_conduct.md

### To Reproduce
1. Go to https://github.com/anitab-org/open-source-programs-backend/blob/develop/CODE_OF_CONDUCT.md#6-reporting-guidelines
2. Click on `Reporting Guidelines`
3. See error

### Expected behavior
Link should be updated to https://github.com/anitab-org/open-source-programs-backend/blob/develop/REPORTING_GUIDELINES.md

### Screenshots
![osp-backend-coc-link](https://user-images.githubusercontent.com/54268438/107860013-29616b00-6e63-11eb-887f-344b4d17e97f.gif)

### Desktop (please complete the following information):
 - OS: Any
 - Browser : Any
 - Version : Any

### Additional context
Don't hardcode the links and add relative path to the file.

**Comment by Rahulm2310** [comment]
@isabelcosta This can be a good `First Timers only` issue. Thanks 🙂

**Comment by isabelcosta** [comment]
Thank you @Rahulm2310 for creating this!

**Comment by Srashtimittal** [comment]
@isabelcosta I want to work on this issue. Please assign me.

**Comment by Srashtimittal** [comment]
@isabelcosta I want to work on this issue. Please assign me.

**Comment by codesankalp** [comment]
@Rahulm2310 Can you please update the issue title and correct the typo `code_cf_conduct` to `code_of_conduct`.

**Comment by codesankalp** [comment]
Assigning you @Srashtimittal !!

**Comment by devkapilbansal** [comment]
@Srashtimittal are you working on this?

**Comment by ashwinijha6** [comment]
@codesankalp & @Rahulm2310 clicking on Reporting Guidelines works perfect for. Could u'll check once?

**Comment by codesankalp** [comment]
@ashwinijha6 I think this issue is solved in https://github.com/anitab-org/open-source-programs-backend/pull/113.
I am closing this issue as it is fixed now.

**Comment by ashwinijha6** [comment]
> @ashwinijha6 I think this issue is solved in #113.
> I am closing this issue as it is fixed now.

👍 @codesankalp
