### ISSUE TITLE
docs: Add Setup to run in Windows 

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/open-source-programs-backend#74]
## Description
As a USER for setting up this project locally in windows, I need the database and setup instructions so that I can easily run the project without facing any problem.

## Mocks
![image](https://user-images.githubusercontent.com/66437295/107875448-e5637a00-6ee5-11eb-8737-c6f4754b234d.png)

### Update [Required]
- [ ] Add all the necessary instructions that are required for setting up this project in windows.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by Amulya-coder** [comment]
@isabelcosta can you please label this issue. Thanks 😊.

**Comment by codesankalp** [comment]
@Amulya-coder Can you please update the description for setting up database for windows also?

**Comment by jeeva2812** [comment]
I am interested in taking up this issue. Can you please assign me? @codesankalp  @Amulya-coder  @isabelcosta

**Comment by codesankalp** [comment]
Assigning you @jeeva2812 !

**Comment by jeeva2812** [comment]
I have made the required changes. Please do review @isabelcosta @codesankalp @Amulya-coder
