### ISSUE TITLE
doc: Move all the documentation of open-source-programs-backend to docusaurus

### ISSUE THREAD

**Issue by ashwinijha6** [anitab-org/open-source-programs-backend#75]
### Is your feature request related to a problem? Please describe.
The current documentation of open-source-programs-backend needs to be moved to docusaurus.

### Describe the solution you'd like
[Docusaurus](https://v2.docusaurus.io/) which will help get more focus on the content.

### Describe alternatives you've considered
I've considered no alternative solutions or features.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by ashwinijha6** [comment]
@isabelcosta I would like to work on this issue. Could u pls assign this to me & add the required labels .

**Comment by isabelcosta** [comment]
Assigned to you @ashwinijha6 :)
