### ISSUE TITLE
Mention the correct link to open session minutes on README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-backend#76]
## Description

As a new contributor,
I need read the correct open session notes document (most current one),
so that I can be aware of most recent discussions.

The meeting minutes mentioned is the minutes from GSoC project sessions.
The new link is: https://docs.google.com/document/d/1JSyAr9bO4hJJxFvThvn_LVjW0KcEspXpzvWULRC_xJE/edit

### Update [Required]
- [ ] Add link to current open session minutes
- [ ] Correct the text with link to last gsoc meeting minutes, and refer to it as the old one

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by sahil9001** [comment]
I want to take this issue, can anyone please assign it to me?

**Comment by codesankalp** [comment]
Assigning you @sahil9001 !
