### ISSUE TITLE
Mock Zulip response when running tests

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-backend#82]
## Description
As a developer,
I need to run tests without depending on Zulip 3rd party service,
so that I can keep the test results only dependant on our project code.

The idea is to mock Zulip API client, make sure that we do not depend on this service when running tests.

### Update [Required]
- [ ] Run tests without the need of Zulip API Key

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by devkapilbansal** [comment]
@isabelcosta I would like to look into this

**Comment by isabelcosta** [comment]
Awesome 🎉 Will assign to you @devkapilbansal

**Comment by devkapilbansal** [comment]
@isabelcosta I found these two ways to make tests passed in a pull request.

1. Create a separate environment and passed it in Github Workflow. This way, API KEY can be provided to the pull requests from the fork.
2.  Use class based approach in this [file](https://github.com/anitab-org/open-source-programs-backend/blob/develop/osp/utils/zulip_api.py)
In starting Django checks files using StatReloader and this line gives the error
https://github.com/anitab-org/open-source-programs-backend/blob/706208962f64607fcc95f56f1fa41288f00a2363/osp/utils/zulip_api.py#L5
By using Class based approach we can make sure the line is used only when the apis for zulip stats are called.

Although the 2nd approach will not make it possible to test zulip api's key but we can change workflow to test it when pushed to master.

What should I do?

**Comment by isabelcosta** [comment]
@devkapilbansal i don't quite understand option 1 🤔 
Regarding Option 2, we don't actually want to test zulip API key, do we?
When you mention create a new environment, do you mention a test environment so that the app behaves differently?

Couldn't we use mock patch()? Like here on mentorship backend? https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/tests/cron_job_functions/test_mentorship_completion_cron.py#L106

**Comment by devkapilbansal** [comment]
> @devkapilbansal i don't quite understand option 1 

Regarding option one, the repository secrets are not passed to the pull requets from the fork. So, we can create an environment, imilar to `.env` file and pass the secret from there.

> Regarding Option 2, we don't actually want to test zulip API key, do we?

If that's the case, I will soon make a PR by implementing option 2


> When you mention create a new environment, do you mention a test environment so that the app behaves differently?

It was for passing secrets to the app.

> Couldn't we use mock patch()? Like here on mentorship backend? https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/tests/cron_job_functions/test_mentorship_completion_cron.py#L106

I don't find a way to use mocking here. Although mocking in used for testing purposed, I would separate the zulip API code from other code so that it don't create errors while testing other things.

**Comment by isabelcosta** [comment]
@devkapilbansal are you clarified here? Would love to see your PR soon, as the GitHub actions always failing does not help to believe the PRs are being tested 🙈 Thank you for working on this!
