### ISSUE TITLE
Get SECRET_KEY as an export environment variable

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-backend#84]
## Description
As an owner of the project,
I need `SECRET_KEY` to not be sourced controlled,
so that I can configure it per environment without exposing to the Open Source community.

The `SECRET_KEY` env variable has to be exported instead of being hardcoded on the project.

### Update [Required]
- [ ] Get `SECRET_KEY` from machine environment
- [ ] Document this required environment variable on README
- [ ] Raise value error if this var is not set
- [ ] Write at least 1 unit test for this

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sahil9001** [comment]
Hey @isabelcosta ! can I take this issue?

**Comment by codesankalp** [comment]
Assigning you @sahil9001 :+1:
