### ISSUE TITLE
Make sendgrid email feature optional for development

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-backend#85]
## Description
As a developer,
I need ease of development,
so that I can focus on feature development and avoid wasting thrid party resources for development.

At the moment, we are required to have a sendgrid account to work on the backend locally, and perhaps this is not necessary. If this is purely to send emails, these can be sent on the console. The idea is to make sendgrid usage optional. If we want to test the real feature, we can, if we don't need to receive real emails, then we don't need it.

For this you have to understand what is the exact usage of emails in the app. You can use environment variables to determine if this functionality should or not be used.

sendgrid: https://sendgrid.com/

### Update [Required]
- [ ] Document on README that using SENDGRID is optional
- [ ] Using sendgrid API key should be optional
- [ ] Write at least 1 test for this

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by codesankalp** [comment]
@isabelcosta As no one commented on this issue I would like to work on this issue.

**Comment by isabelcosta** [comment]
Done, this is quite important @codesankalp thank you for working on this!
