### ISSUE TITLE
Improve function naming and create docstrings and type hint for zulip_api.py

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-backend#86]
## Description
As a developer,
I need code easy to understand,
so that I can develop more efficiently.

The scope of that issue is strict to `osp/utils/zulip_api.py` file, it may include changes on other files if it involves function name changes.

I noticed that one of the functions is called `get_messages()` which implies the return value is a collection of messages. This is not true, the function returns the number of messages. So the name of the function is misleading.

Also, this interface of communication with Zulip API has specific logic needed for the project. To enhance the readability of this part of the code, I suggest adding docstrings to this file as well as typehints

### Update [Required]
- [ ] Add type hints to every function on `zulip_api.py`
- [ ] Add doc string to every function on `zulip_api.py` to better explain their purpose, input and output
- [ ] Rename functions that need change (e.g.: `get_messages()` -> `get_total_messages()`)

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by imperishableSecret** [comment]
@isabelcosta Can I work on this issue?

**Comment by codesankalp** [comment]
Assigning you @AnubhavHooda !

**Comment by b-thebest** [comment]
Can I work on this issue ?

**Comment by codesankalp** [comment]
@b-thebest As this issue is already assigned to @AnubhavHooda . Please look into another issue.
