### ISSUE TITLE
Get Database configuration as an export environment variable.

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-backend#88]
## Description
As a contributor,
I need database  configuration to be exported as separate environment variables 
so that changing database configuration for deployed as well as the local project does not depend on changing code every time.

### Update [Required]
- [ ] Get `DB_NAME`, `DB_USERNAME`, `DB_PASSWORD`, `DB_HOST`, `DB_PORT`  from machine environments.
- [ ] Document these environment variables on README with the appropriate value for setting up the project.
- [ ] Raise value error if env variables are not exported or found.
- [ ] Write at least one unit-test to test it.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by codesankalp** [comment]
@isabelcosta Can you please add labels to it?

**Comment by NenadPantelic** [comment]
@isabelcosta  Can I work on it?

**Comment by Amulya-coder** [comment]
@NenadPantelic you are already assigned to #60.

**Comment by NenadPantelic** [comment]
@Amulya-coder Oh sorry, I totally overlooked that, I don't know  how :facepalm:

**Comment by ashwinijha6** [comment]
Hey @isabelcosta could you pls assign me this issue I would like to work on this

**Comment by NeerajSati** [comment]
Can I Work on this?

**Comment by codesankalp** [comment]
As @ashwinijha6 You are already assigned to an issue, I am assigning this to @NeerajSati.
@NeerajSati Assigning you!!

**Comment by codesankalp** [comment]
@ashwinijha6 Assigning this to you. :rocket:

**Comment by isabelcosta** [comment]
@ashwinijha6 are you still interested in this issue? I will unassign due to almost one month's of inactivity. Let me know if you interested, and we can assign again.

**Comment by ashwinijha6** [comment]
> @ashwinijha6 are you still interested in this issue? I will unassign due to almost one month's of inactivity. Let me know if you interested, and we can assign again.

I'm so sorry for the delay @isabelcosta. I'm a bit busy at the moment you can unassign me & make it available for others.

**Comment by isabelcosta** [comment]
No problem at all @ashwinijha6 :) Good luck with your other commitments 🙏🏾  you're always welcome to come and contribute 🤗

**Comment by ashwinijha6** [comment]
> No problem at all @ashwinijha6 :) Good luck with your other commitments 🙏🏾 you're always welcome to come and contribute 🤗

Thankyou for understanding @isabelcosta. I'll surely be back once I finish up my work ❤️

**Comment by codesankalp** [comment]
As https://github.com/anitab-org/anitab-forms-backend/pull/109 PR is almost complete I can work on this. What do you think @isabelcosta?

**Comment by isabelcosta** [comment]
Yes @codesankalp I think this could be useful to contributors to get this solved.
