### ISSUE TITLE
Create the config.yml file for the Welcome Bot 

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/open-source-programs-backend#89]
## Description
As a first time contributor,
I need a bot to help guide my first contribution,
so that I can follow this org's contribution guidelines.

## Mocks
![image](https://user-images.githubusercontent.com/66437295/108079251-a293d480-7094-11eb-93ee-992b1aaa5fb3.png)

### Update [Required]
- [ ] newIssueWelcomeComment is complete with the correct links to this repo.
- [ ] newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.
- [ ] firstPRMergeComment is complete.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
[0.5] hours

**Comment by Amulya-coder** [comment]
@isabelcosta can you please label this issue.

**Comment by himanshu007-creator** [comment]
HI @Amulya-coder I would like to work on this issue!

**Comment by Amulya-coder** [comment]
@Aaishpra can you please assign it to @himanshu007-creator.

**Comment by Aaishpra** [comment]
@himanshu007-creator you are assigned 🚀

**Comment by himanshu007-creator** [comment]
I am facing some problem. The bot that i created is working fine. But it is <b>failing build tests</b>.
i am using <code>runs-on : ubuntu-latest</code>
PREVIEW:-
![2021-02-26 (2)](https://user-images.githubusercontent.com/65963997/109314307-2d33bb00-786f-11eb-9e0d-b5b629a8dd9f.png)
ERROR:-
![2021-02-26](https://user-images.githubusercontent.com/65963997/109313714-85b68880-786e-11eb-8002-700b72016f90.png)

I tried replacing the code with <code>runs-on : ubuntu-20.04</code> but still the build fails.

**Comment by codesankalp** [comment]
@himanshu007-creator The test will fail, for now, You can create a PR with a failing test.
