### ISSUE TITLE
docs: Add General Guidelines in the CONTRIBUTING.md

### ISSUE THREAD

**Issue by khushishikhu** [anitab-org/open-source-programs-backend#90]
### Is your feature request related to a problem? Please describe.
Write general guidelines in the CONTRIBUTING.md

### Describe the solution you'd like
For reference check [here](https://github.com/anitab-org/open-source-programs-backend/blob/develop/.github/CONTRIBUTING.md)

**Comment by devkapilbansal** [comment]
HI @khushishikhu can you please explain what you mean by `general guidelines`?

**Comment by codesankalp** [comment]
@khushishikhu Please describe the issue in detail by writing a brief description of the issue.

**Comment by codesankalp** [comment]
@khushishikhu Can you please edit the issue description?

**Comment by ashwinijha6** [comment]
@codesankalp & @devkapilbansal  I guess @khushishikhu means to say the `general guidelines` as mentioned in [here](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md), could be taken as a reference.
I could work on this.

**Comment by codesankalp** [comment]
Okay, @ashwinijha6, Now I understand. @khushishikhu Can you edit the issue description and add the link as mentioned by @ashwinijha6. 
I am adding labels and making it a first-timer issue.
@ashwinijha6 There is an issue already assigned to you. So I can't assign it to you for now.

**Comment by khushishikhu** [comment]
@codesankalp sure I will edit the description of the issue . Sorry for the late reply actually I have been indulged with my university exams . Thank you for adding the labels

**Comment by aakankshaagr** [comment]
@khushishikhu I would like to work on this issue.

**Comment by codesankalp** [comment]
Assigning you @aakankshaagr.

**Comment by ashwinijha6** [comment]
Any updates on this @aakankshaagr ?

**Comment by aakankshaagr** [comment]
Sorry, @ashwinijha6 I forgot to update. This is the first time I am documenting. I have followed the reference and made updates in contributing.md. I am just looking for more guidelines that I can place.

**Comment by aakankshaagr** [comment]
@ashwinijha6 I am creating a PR so that it would be easy for everyone to review.

**Comment by ashwinijha6** [comment]
> @ashwinijha6 I am creating a PR so that it would be easy for everyone to review.

Yeah sure @aakankshaagr
