### ISSUE TITLE
docs: Improve Pull request templates

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/open-source-programs-backend#91]
### Is your feature request related to a problem? Please describe.
As I saw in the Issue template there are descriptions like `A clear and concise description of what you want to happen.` which is also shown in the preview window unless I remove it manually so it was a time taking process, the description like above should be commented as they are for Author's eye only.
Also, remove the irrelevant options like `I have written Kotlin Docs whenever is applicable`  under the checklist.

### Describe the solution you'd like
It should be commented like this `<!-- A clear and concise description of what you want to happen. -->`

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by Amulya-coder** [comment]
@isabelcosta can you please look into this after approving I would like to be assigned.

**Comment by Rahulm2310** [comment]
@Amulya-coder This is a newcomer friendly issue. Let's give them a chance. As you have already contributed in past, please look for some other available issues. 

Cc: @isabelcosta

**Comment by isabelcosta** [comment]
@Amulya-coder could you share this on Zulip, so that new contributors have the chance to contribute to this project? There are other issues which are available, could you look into those? Do you need help picking one?

**Comment by Amulya-coder** [comment]
Sure! @isabelcosta I would share all the beginner's friendly issues on Zulip thanks for giving me this opportunity.

**Comment by isabelcosta** [comment]
I changed the title of the issue, because I will create another issue to remove the issue templates folder :)

**Comment by Subhangini** [comment]
Assign this issue to me .I would like to work on this

**Comment by isabelcosta** [comment]
@Subhangini assigned you the other first timer only issue #69 ;)

**Comment by 17sushmita** [comment]
Can this issue be assigned to me? I would like to work on it.

**Comment by codesankalp** [comment]
Assigning you @17sushmita

**Comment by Rahulm2310** [comment]
@Amulya-coder can you please add the following point as well in the issue description as we have closed #105.
- There is a option `I have written Kotlin Docs whenever is applicable` under the checklist in PULL_REQUEST_TEMPLATE.md. (I think due to copy-pasting the file from some other project). This should be removed.

**Comment by Amulya-coder** [comment]
> @Amulya-coder can you please add the following point as well in the issue description as we have closed #105.
> 
> * There is a option `I have written Kotlin Docs whenever is applicable` under the checklist in PULL_REQUEST_TEMPLATE.md. (I think due to copy-pasting the file from some other project). This should be removed.

Updated @Rahulm2310
