### ISSUE TITLE
Delete .github/ISSUE_TEMPLATE folder

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-backend#97]
## Description

As a org admin / maintainer,
I need to maintain 1 version of issue templates used in the organization,
so that I can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Update [Required]
- [ ] Delete `.github/ISSUE_TEMPLATE`

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by shriya030** [comment]
Can I work on this issue?

**Comment by Pranathi-star** [comment]
Delete ISSUE_TEMPLATE folder

**Comment by Pranathi-star** [comment]
Can I work on this?

**Comment by Aaishpra** [comment]
> Can I work on this issue?

Assigned you, @shriya030 good luck 🎉
